### ISSUE TITLE
Can I use Facematch to find user pics from my albums?

### ISSUE THREAD

**Issue by andrerpena** [louisondumont/facematch#4]
Hey. Awesome job. Thanks.

I was wondering if this use-case would be feasible:
- I have Facebook a page with albums with lots of picture of random people. I also have a website.
- User X logs in one my website using their own Facebook account.
- Facematch tries to find user X pictures among the pictures of my Facebook page.

That is probably not possible yet. Doesn't hurt to ask though.

Thanks again.

**Comment by louisondumont** [comment]
Facebook's face recognition only works with your friends. Which means you would have to friend your users to recognize them.
