### ISSUE TITLE
Error getting imgUrl and accessToken (undefined:1)

### ISSUE THREAD

**Issue by TorranceYang** [louisondumont/facematch#7]
I've located the source of a couple small errors. Lines 11 and 12 in /lib/recognize.js should be

`var imgUrl = req.query.url,
      accessToken = req.query.accessToken;`

Also, if you're still have trouble, the problem might be your accessToken. Be sure to allow your facebook app to post for you!

**Comment by louisondumont** [comment]
Errors? The readme says POST, not GET.
